-- Inserción en la tabla SPAS
INSERT INTO SPAS (ID, DURACION, COSTO, CAPACIDAD, DISPONIBILIDAD)
VALUES (1, 60, 100.0, 10, 1);

-- Inserción en la tabla PRODUCTOS
INSERT INTO PRODUCTOS (ID, COSTO, NOMBRE)
VALUES (1, 10.0, 'Champú');

-- Inserción en la tabla USUARIOS
INSERT INTO USUARIOS (ID, NOMBRE, DOCUMENTO, TIPODOCUMENTO, ROL, CORREO, CONTRASENA)
VALUES (1, 'Juan Pérez', '12345678', 'DNI', 'Cliente', 'juan@example.com', 'contraseña123');

-- Inserción en la tabla HOTELES
INSERT INTO HOTELES (ID, NOMBRE, TIPO, ESTRELLAS, CATEGORIA, CIUDAD)
VALUES (1, 'Hotel Ejemplo', 'Lujo', 5, 'Cinco Estrellas', 'Ciudad Ejemplo');

-- Inserción en la tabla PLANES
INSERT INTO PLANES (ID, TIPO, HORARIO, DESCRIPCION)
VALUES (1, 'Plan Básico', TO_DATE('2023-10-01', 'YYYY-MM-DD'), 'Plan de alojamiento estándar');


-- Inserción en la tabla HABITACIONES
INSERT INTO HABITACIONES (ID, CAPACIDAD, TIPO, DOTACION, PRECIONOCHE, CONSUMOEXTRA, HOTELID)
VALUES (101, 2, 'Doble', 'TV, Wi-Fi, Baño privado', 80.0, 10.0, 1);

-- Inserción en la tabla RESERVAS
INSERT INTO RESERVAS (ID, FECHA, FECHAFINAL, PERSONAS, HABTACIONID, PLANESID, USUARIOID)
VALUES (1, TO_DATE('2023-10-01', 'YYYY-MM-DD'), TO_DATE('2023-10-05', 'YYYY-MM-DD'), 2, 101, 1, 1);

-- Inserción en la tabla LAVANDERIAS
INSERT INTO LAVANDERIAS (ID, TIPOPRENDA, NUMEROPRENDAS, PARESZAPATOS, COSTO)
VALUES (1, 'Camisa', 5, 2, 15.0);

-- Inserción en la tabla SALONES
INSERT INTO SALONES (ID, CAPACIDAD, TIPO, COSTOHORA, LIMPIEZA, EQUIPOS)
VALUES (1, 50, 'Conferencia', 150.0, 4, 1);

-- Inserción en la tabla SERVICIORESERVAS
INSERT INTO SERVICIORESERVAS (ID, FECHAINICIAL, FECHAFINAL, IDHABITACION, IDSPA, IDSALON, IDLAVANDERIA)
VALUES (1, TO_DATE('2023-10-01', 'YYYY-MM-DD'), TO_DATE('2023-10-05', 'YYYY-MM-DD'), 101, 1, 1, 1);

-- Inserción en la tabla UTILERIA
INSERT INTO UTILERIA (ID, NOMBRE, COSTOPENALIZACION)
VALUES (1, 'Toalla', 5.0);

-- Inserción en la tabla FACTURAS
INSERT INTO FACTURAS (ID, precioTotal)
VALUES (1, 200.0);

-- Inserción en la tabla REGISTROS
INSERT INTO REGISTROS (ID, LLEGADA, SALIDA, IDRESERVA, IDUSUARIO)
VALUES (1, TO_DATE('2023-10-01', 'YYYY-MM-DD'), TO_DATE('2023-10-05', 'YYYY-MM-DD'), 1, 1);

-- Inserción en la tabla PISCINA
INSERT INTO PISCINA (ID, PROFUNDIDAD, COSTO, CAPACIDAD, DISPONIBILDAD, HOTELID)
VALUES (1, 2.0, 10.0, 50, 'Disponible', 1);

-- Inserción en la tabla INTERNET
INSERT INTO INTERNET (ID, CAPACIDAD, COSTODIARIO, HOTELID)
VALUES (1, 100, 5.0, 1);

-- Inserción en la tabla GIMNASIO
INSERT INTO GIMNASIO (ID, MAQUINAS, HORARIO, CAPACIDAD, HOTELID)
VALUES (1, 20, '06:00 - 22:00', 30, 1);

-- Inserción en la tabla BARES
INSERT INTO BARES (ID, CAPACIDAD, ESTILO, NOMBRE, HOTELID)
VALUES (1, 50, 'Pub', 'Bar del Hotel', 1);

-- Inserción en la tabla RESTAURANTES
INSERT INTO RESTAURANTES (ID, CAPACIDAD, ESTILO, NOMBRE, HOTELID)
VALUES (1, 100, 'Gourmet', 'Restaurante del Hotel', 1);

-- Inserción en la tabla SUPERMERCADOS
INSERT INTO SUPERMERCADOS (ID, NOMBRE, HOTELID)
VALUES (1, 'Supermercado del Hotel', 1);

-- Inserción en la tabla TIENDAS
INSERT INTO TIENDAS (ID, NOMBRE, HOTELID)
VALUES (1, 'Tienda de Regalos', 1);

commit;