
--REQ F5
SELECT U.NOMBRE AS NOMBRE_USUARIO, P.NOMBRE AS NOMBRE_PRODUCTO, SC.COSTO AS COSTO_CONSUMO, SC.FECHA
FROM SERVICIOSCONSUMO SC
JOIN PRODUCTOS P ON SC.IDPRODUCTO = P.ID
JOIN RESERVAS R ON SC.IDHABITACION = R.HABTACIONID
JOIN USUARIOS U ON R.USUARIOID = U.ID
WHERE U.ID = 3
  AND SC.FECHA BETWEEN TO_DATE('2023-01-01', 'YYYY-MM-DD') AND TO_DATE('2023-02-28', 'YYYY-MM-DD');


--REQ F6

--Fechas de Mayor Ocupación:
SELECT FECHA, COUNT(*) AS HABITACIONES_OCUPADAS
FROM RESERVAS
GROUP BY FECHA
ORDER BY HABITACIONES_OCUPADAS DESC;

--Fechas de Mayores Ingresos (Mayor cantidad de consumos realizados):
SELECT SC.FECHA, SUM(SC.COSTO) AS INGRESOS
FROM SERVICIOSCONSUMO SC
GROUP BY SC.FECHA
ORDER BY INGRESOS DESC;


--Fechas de Menor Demanda (Menor ocupación)
SELECT FECHA, COUNT(*) AS HABITACIONES_OCUPADAS
FROM RESERVAS
GROUP BY FECHA
ORDER BY HABITACIONES_OCUPADAS ASC;

--REQ F7

--Clientes que han estado en el hotel al menos dos semanas:

SELECT U.NOMBRE AS NOMBRE_CLIENTE, R.USUARIOID, SUM(R.FECHAFINAL - R.FECHA) AS TOTAL_DIAS
FROM RESERVAS R
JOIN USUARIOS U ON R.USUARIOID = U.ID
GROUP BY U.NOMBRE, R.USUARIOID
HAVING SUM(R.FECHAFINAL - R.FECHA) >= 14;


--Clientes que han consumido más de $15,000,000.00 en el último año:

SELECT U.NOMBRE AS NOMBRE_CLIENTE, R.USUARIOID, SUM(SC.COSTO) AS TOTAL_CONSUMO
FROM SERVICIOSCONSUMO SC
JOIN RESERVAS R ON SC.IDHABITACION = R.HABTACIONID
JOIN USUARIOS U ON R.USUARIOID = U.ID
WHERE SC.FECHA >= SYSDATE - 365 -- Para el último año
GROUP BY U.NOMBRE, R.USUARIOID
HAVING SUM(SC.COSTO) > 15000000;


--REQ F8
SELECT s.TIPO AS SERVICIO, COUNT(*) AS FRECUENCIA_TOTAL
FROM SERVICIORESERVAS s
WHERE FECHAINICIAL >= ADD_MONTHS(SYSDATE, -12)  -- Filtrar reservas del último año
GROUP BY s.TIPO
HAVING COUNT(*) < 3;


